#!/bin/sh

echo "==> Provide angular application..."

frontendProjectName=$(ls "$1")
frontendDistDirectory="$1/$frontendProjectName/dist/$frontendProjectName/*"

rm -rf  $2
[[ -d $2 ]] | mkdir $2

cp $frontendDistDirectory $2
